services:
  api:
    build: ./scraper
    ports:
      - "8000:8000"
    image: scraper_api:latest
    container_name: scraper_api
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-stock-data:/data/db

volumes:
  mongo-stock-data:
